import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import Head from "next/head";
import { useWindowSize } from "usehooks-ts";

const Home = () => {
  const { width } = useWindowSize();
  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {width > 767 && <Navigation />}
      </main>
    </>
  );
};

export default Home;
